# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gocosi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgocosi.proto\" \n\x0fRegisterNodeReq\x12\r\n\x05nodes\x18\x01 \x01(\t\"\x18\n\tNewMsgReq\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x84\x01\n\x06Gossip\x12\x0c\n\x04subs\x18\x01 \x03(\t\x12\x0e\n\x06unsubs\x18\x02 \x03(\t\x12*\n\nevent_list\x18\x03 \x03(\x0b\x32\x16.Gossip.EventListEntry\x1a\x30\n\x0e\x45ventListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"q\n\x08InfoResp\x12\x0c\n\x04subs\x18\x01 \x03(\t\x12\x0e\n\x06unsubs\x18\x02 \x03(\t\x12\x0e\n\x06pubkey\x18\x03 \x03(\t\x12\x0f\n\x07latency\x18\x04 \x03(\x01\x12\x12\n\nround_time\x18\x05 \x01(\t\x12\x12\n\nneighbours\x18\x06 \x01(\x05\"v\n\rGetPubkeyResp\x12\x32\n\npublickeys\x18\x01 \x03(\x0b\x32\x1e.GetPubkeyResp.PublickeysEntry\x1a\x31\n\x0fPublickeysEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"z\n\nNewMsgResp\x12\x11\n\tsignature\x18\x01 \x01(\t\x12)\n\x07signers\x18\x02 \x03(\x0b\x32\x18.NewMsgResp.SignersEntry\x1a.\n\x0cSignersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x1d\n\nCommonResp\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xca\x01\n\tGocosiRPC\x12/\n\x0cRegisterNode\x12\x10.RegisterNodeReq\x1a\x0b.CommonResp\"\x00\x12#\n\x06NewMsg\x12\n.NewMsgReq\x1a\x0b.NewMsgResp\"\x00\x12#\n\tGossipReq\x12\x07.Gossip\x1a\x0b.CommonResp\"\x00\x12\x1b\n\x04Info\x12\x06.Empty\x1a\t.InfoResp\"\x00\x12%\n\tGetPubkey\x12\x06.Empty\x1a\x0e.GetPubkeyResp\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gocosi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GOSSIP_EVENTLISTENTRY._options = None
  _GOSSIP_EVENTLISTENTRY._serialized_options = b'8\001'
  _GETPUBKEYRESP_PUBLICKEYSENTRY._options = None
  _GETPUBKEYRESP_PUBLICKEYSENTRY._serialized_options = b'8\001'
  _NEWMSGRESP_SIGNERSENTRY._options = None
  _NEWMSGRESP_SIGNERSENTRY._serialized_options = b'8\001'
  _REGISTERNODEREQ._serialized_start=16
  _REGISTERNODEREQ._serialized_end=48
  _NEWMSGREQ._serialized_start=50
  _NEWMSGREQ._serialized_end=74
  _GOSSIP._serialized_start=77
  _GOSSIP._serialized_end=209
  _GOSSIP_EVENTLISTENTRY._serialized_start=161
  _GOSSIP_EVENTLISTENTRY._serialized_end=209
  _INFORESP._serialized_start=211
  _INFORESP._serialized_end=324
  _GETPUBKEYRESP._serialized_start=326
  _GETPUBKEYRESP._serialized_end=444
  _GETPUBKEYRESP_PUBLICKEYSENTRY._serialized_start=395
  _GETPUBKEYRESP_PUBLICKEYSENTRY._serialized_end=444
  _NEWMSGRESP._serialized_start=446
  _NEWMSGRESP._serialized_end=568
  _NEWMSGRESP_SIGNERSENTRY._serialized_start=522
  _NEWMSGRESP_SIGNERSENTRY._serialized_end=568
  _COMMONRESP._serialized_start=570
  _COMMONRESP._serialized_end=599
  _EMPTY._serialized_start=601
  _EMPTY._serialized_end=608
  _GOCOSIRPC._serialized_start=611
  _GOCOSIRPC._serialized_end=813
# @@protoc_insertion_point(module_scope)
